/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedAccountRouteRouteImport } from './routes/_authenticated/_account/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedPSlugRouteRouteImport } from './routes/_authenticated/p/$slug/route'
import { Route as AuthenticatedAccountSettingsIndexRouteImport } from './routes/_authenticated/_account/settings/index'
import { Route as AuthenticatedAccountDashboardIndexRouteImport } from './routes/_authenticated/_account/dashboard/index'
import { Route as AuthenticatedPSlugStandingsIndexRouteImport } from './routes/_authenticated/p/$slug/standings/index'
import { Route as AuthenticatedPSlugSettingsIndexRouteImport } from './routes/_authenticated/p/$slug/settings/index'
import { Route as AuthenticatedPSlugRosterIndexRouteImport } from './routes/_authenticated/p/$slug/roster/index'
import { Route as AuthenticatedPSlugLiveIndexRouteImport } from './routes/_authenticated/p/$slug/live/index'
import { Route as AuthenticatedPSlugDashboardIndexRouteImport } from './routes/_authenticated/p/$slug/dashboard/index'
import { Route as AuthenticatedPSlugAdminIndexRouteImport } from './routes/_authenticated/p/$slug/admin/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRouteRoute =
  AuthenticatedAccountRouteRouteImport.update({
    id: '/_account',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPSlugRouteRoute = AuthenticatedPSlugRouteRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountSettingsIndexRoute =
  AuthenticatedAccountSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedAccountRouteRoute,
  } as any)
const AuthenticatedAccountDashboardIndexRoute =
  AuthenticatedAccountDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedAccountRouteRoute,
  } as any)
const AuthenticatedPSlugStandingsIndexRoute =
  AuthenticatedPSlugStandingsIndexRouteImport.update({
    id: '/standings/',
    path: '/standings/',
    getParentRoute: () => AuthenticatedPSlugRouteRoute,
  } as any)
const AuthenticatedPSlugSettingsIndexRoute =
  AuthenticatedPSlugSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedPSlugRouteRoute,
  } as any)
const AuthenticatedPSlugRosterIndexRoute =
  AuthenticatedPSlugRosterIndexRouteImport.update({
    id: '/roster/',
    path: '/roster/',
    getParentRoute: () => AuthenticatedPSlugRouteRoute,
  } as any)
const AuthenticatedPSlugLiveIndexRoute =
  AuthenticatedPSlugLiveIndexRouteImport.update({
    id: '/live/',
    path: '/live/',
    getParentRoute: () => AuthenticatedPSlugRouteRoute,
  } as any)
const AuthenticatedPSlugDashboardIndexRoute =
  AuthenticatedPSlugDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedPSlugRouteRoute,
  } as any)
const AuthenticatedPSlugAdminIndexRoute =
  AuthenticatedPSlugAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AuthenticatedPSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/p/$slug': typeof AuthenticatedPSlugRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/': typeof AuthenticatedAccountDashboardIndexRoute
  '/settings/': typeof AuthenticatedAccountSettingsIndexRoute
  '/p/$slug/admin/': typeof AuthenticatedPSlugAdminIndexRoute
  '/p/$slug/dashboard/': typeof AuthenticatedPSlugDashboardIndexRoute
  '/p/$slug/live/': typeof AuthenticatedPSlugLiveIndexRoute
  '/p/$slug/roster/': typeof AuthenticatedPSlugRosterIndexRoute
  '/p/$slug/settings/': typeof AuthenticatedPSlugSettingsIndexRoute
  '/p/$slug/standings/': typeof AuthenticatedPSlugStandingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/p/$slug': typeof AuthenticatedPSlugRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard': typeof AuthenticatedAccountDashboardIndexRoute
  '/settings': typeof AuthenticatedAccountSettingsIndexRoute
  '/p/$slug/admin': typeof AuthenticatedPSlugAdminIndexRoute
  '/p/$slug/dashboard': typeof AuthenticatedPSlugDashboardIndexRoute
  '/p/$slug/live': typeof AuthenticatedPSlugLiveIndexRoute
  '/p/$slug/roster': typeof AuthenticatedPSlugRosterIndexRoute
  '/p/$slug/settings': typeof AuthenticatedPSlugSettingsIndexRoute
  '/p/$slug/standings': typeof AuthenticatedPSlugStandingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/_account': typeof AuthenticatedAccountRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/_authenticated/p/$slug': typeof AuthenticatedPSlugRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/_account/dashboard/': typeof AuthenticatedAccountDashboardIndexRoute
  '/_authenticated/_account/settings/': typeof AuthenticatedAccountSettingsIndexRoute
  '/_authenticated/p/$slug/admin/': typeof AuthenticatedPSlugAdminIndexRoute
  '/_authenticated/p/$slug/dashboard/': typeof AuthenticatedPSlugDashboardIndexRoute
  '/_authenticated/p/$slug/live/': typeof AuthenticatedPSlugLiveIndexRoute
  '/_authenticated/p/$slug/roster/': typeof AuthenticatedPSlugRosterIndexRoute
  '/_authenticated/p/$slug/settings/': typeof AuthenticatedPSlugSettingsIndexRoute
  '/_authenticated/p/$slug/standings/': typeof AuthenticatedPSlugStandingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/callback'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/p/$slug'
    | '/api/auth/$'
    | '/dashboard/'
    | '/settings/'
    | '/p/$slug/admin/'
    | '/p/$slug/dashboard/'
    | '/p/$slug/live/'
    | '/p/$slug/roster/'
    | '/p/$slug/settings/'
    | '/p/$slug/standings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/p/$slug'
    | '/api/auth/$'
    | '/dashboard'
    | '/settings'
    | '/p/$slug/admin'
    | '/p/$slug/dashboard'
    | '/p/$slug/live'
    | '/p/$slug/roster'
    | '/p/$slug/settings'
    | '/p/$slug/standings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/_account'
    | '/auth/callback'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/_authenticated/p/$slug'
    | '/api/auth/$'
    | '/_authenticated/_account/dashboard/'
    | '/_authenticated/_account/settings/'
    | '/_authenticated/p/$slug/admin/'
    | '/_authenticated/p/$slug/dashboard/'
    | '/_authenticated/p/$slug/live/'
    | '/_authenticated/p/$slug/roster/'
    | '/_authenticated/p/$slug/settings/'
    | '/_authenticated/p/$slug/standings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_account': {
      id: '/_authenticated/_account'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAccountRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/p/$slug': {
      id: '/_authenticated/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof AuthenticatedPSlugRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_account/settings/': {
      id: '/_authenticated/_account/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedAccountSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedAccountRouteRoute
    }
    '/_authenticated/_account/dashboard/': {
      id: '/_authenticated/_account/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedAccountDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedAccountRouteRoute
    }
    '/_authenticated/p/$slug/standings/': {
      id: '/_authenticated/p/$slug/standings/'
      path: '/standings'
      fullPath: '/p/$slug/standings/'
      preLoaderRoute: typeof AuthenticatedPSlugStandingsIndexRouteImport
      parentRoute: typeof AuthenticatedPSlugRouteRoute
    }
    '/_authenticated/p/$slug/settings/': {
      id: '/_authenticated/p/$slug/settings/'
      path: '/settings'
      fullPath: '/p/$slug/settings/'
      preLoaderRoute: typeof AuthenticatedPSlugSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedPSlugRouteRoute
    }
    '/_authenticated/p/$slug/roster/': {
      id: '/_authenticated/p/$slug/roster/'
      path: '/roster'
      fullPath: '/p/$slug/roster/'
      preLoaderRoute: typeof AuthenticatedPSlugRosterIndexRouteImport
      parentRoute: typeof AuthenticatedPSlugRouteRoute
    }
    '/_authenticated/p/$slug/live/': {
      id: '/_authenticated/p/$slug/live/'
      path: '/live'
      fullPath: '/p/$slug/live/'
      preLoaderRoute: typeof AuthenticatedPSlugLiveIndexRouteImport
      parentRoute: typeof AuthenticatedPSlugRouteRoute
    }
    '/_authenticated/p/$slug/dashboard/': {
      id: '/_authenticated/p/$slug/dashboard/'
      path: '/dashboard'
      fullPath: '/p/$slug/dashboard/'
      preLoaderRoute: typeof AuthenticatedPSlugDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedPSlugRouteRoute
    }
    '/_authenticated/p/$slug/admin/': {
      id: '/_authenticated/p/$slug/admin/'
      path: '/admin'
      fullPath: '/p/$slug/admin/'
      preLoaderRoute: typeof AuthenticatedPSlugAdminIndexRouteImport
      parentRoute: typeof AuthenticatedPSlugRouteRoute
    }
  }
}

interface AuthenticatedAccountRouteRouteChildren {
  AuthenticatedAccountDashboardIndexRoute: typeof AuthenticatedAccountDashboardIndexRoute
  AuthenticatedAccountSettingsIndexRoute: typeof AuthenticatedAccountSettingsIndexRoute
}

const AuthenticatedAccountRouteRouteChildren: AuthenticatedAccountRouteRouteChildren =
  {
    AuthenticatedAccountDashboardIndexRoute:
      AuthenticatedAccountDashboardIndexRoute,
    AuthenticatedAccountSettingsIndexRoute:
      AuthenticatedAccountSettingsIndexRoute,
  }

const AuthenticatedAccountRouteRouteWithChildren =
  AuthenticatedAccountRouteRoute._addFileChildren(
    AuthenticatedAccountRouteRouteChildren,
  )

interface AuthenticatedPSlugRouteRouteChildren {
  AuthenticatedPSlugAdminIndexRoute: typeof AuthenticatedPSlugAdminIndexRoute
  AuthenticatedPSlugDashboardIndexRoute: typeof AuthenticatedPSlugDashboardIndexRoute
  AuthenticatedPSlugLiveIndexRoute: typeof AuthenticatedPSlugLiveIndexRoute
  AuthenticatedPSlugRosterIndexRoute: typeof AuthenticatedPSlugRosterIndexRoute
  AuthenticatedPSlugSettingsIndexRoute: typeof AuthenticatedPSlugSettingsIndexRoute
  AuthenticatedPSlugStandingsIndexRoute: typeof AuthenticatedPSlugStandingsIndexRoute
}

const AuthenticatedPSlugRouteRouteChildren: AuthenticatedPSlugRouteRouteChildren =
  {
    AuthenticatedPSlugAdminIndexRoute: AuthenticatedPSlugAdminIndexRoute,
    AuthenticatedPSlugDashboardIndexRoute:
      AuthenticatedPSlugDashboardIndexRoute,
    AuthenticatedPSlugLiveIndexRoute: AuthenticatedPSlugLiveIndexRoute,
    AuthenticatedPSlugRosterIndexRoute: AuthenticatedPSlugRosterIndexRoute,
    AuthenticatedPSlugSettingsIndexRoute: AuthenticatedPSlugSettingsIndexRoute,
    AuthenticatedPSlugStandingsIndexRoute:
      AuthenticatedPSlugStandingsIndexRoute,
  }

const AuthenticatedPSlugRouteRouteWithChildren =
  AuthenticatedPSlugRouteRoute._addFileChildren(
    AuthenticatedPSlugRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRouteRoute: typeof AuthenticatedAccountRouteRouteWithChildren
  AuthenticatedPSlugRouteRoute: typeof AuthenticatedPSlugRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRouteRoute: AuthenticatedAccountRouteRouteWithChildren,
  AuthenticatedPSlugRouteRoute: AuthenticatedPSlugRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
